name: Check Security Alert Age

# on:
#   pull_request:
#     types: [opened, edited, synchronize]

on:
  workflow_dispatch:

jobs:
  security-check:
    uses: transurban/github-action-templates/.github/workflows/vulnerability-sla-remediation-action.yml@Add-New-Github-Rulesets